# codegen.py
import subprocess
import yaml
import os
class NameGenerator:
    def __init__(self,variable_name):
        self.id = 0
        self.variable_name = variable_name
    def next(self):
        self.id += 1
        return self.variable_name + str(self.id)
variable_name_generator = {}

# filename('/path/to/cool-file.txt') = 'cool-file'
def filename(filepath):
    return os.path.splitext(os.path.basename(obj_filename))[0]

# construct a C++ assignment statement
# assign('steve','favorite_color','green') = 'steve->favorite_color = green;'
def assign(owner,field,value):
    if(type(value) == str):
        value = '"' + value + '"'
    return owner + '->' + field + ' = ' + str(value) + ';\n'

# construct a C++ declare/initialize statement
def declare(var_type, var_name):
    return var_type + "* " + var_name + " = new " + var_type + "();\n"

def add_component(owner_name, var_name):
    return owner_name + "->addComponent(" + var_name + ");\n"

def component_code(component, owner_name):
    print(component)
    result = ""
    spaces = "        "
    component_type = component
    if(type(component) == dict):
        component_type = list(component.keys())[0]
    if component_type not in variable_name_generator:
        variable_name_generator[component_type] = NameGenerator(component_type)
    component_name = variable_name_generator[component_type].next()
    result += spaces + declare(component_type,component_name)
    if(type(component) == dict):
        fields = component[component_type]
        for field in fields:
            result += spaces + assign(component_name, field, fields[field])
    result += spaces + add_component(owner_name, component_name)
    return result

header = """#ifndef GAMEOBJECTS_H
#define GAMEOBJECTS_H
// AUTOGENERATED GameObject variants from .object files
using namespace std;

#include "GameObject.h"
"""

components_needed = set()
classes_declared = set()

classes = ""
obj_filenames = subprocess.run('find ./src -name *.object'.split(), capture_output=True).stdout.decode('ascii').split('\n')[:-1]
for obj_filename in sorted(obj_filenames):
    with open(obj_filename, 'r') as obj_file:
        class_name = filename(obj_filename)
        classes_declared.add(class_name)
        constructor_code = ""
        components = yaml.safe_load(obj_file.read())
        for component in components:
            component_type = component
            if(type(component) == dict):
                component_type = list(component.keys())[0]
            components_needed.add(component_type)
            constructor_code += component_code(component, 'this')
            #TODO: handle child GameObjects
        class_code = """
class Example: public GameObject {
public:
    Example() { 
INITIALIZATION
    }
};
        """.replace("Example",class_name).replace("INITIALIZATION",constructor_code.rstrip())
        classes += class_code

component_includes = ""
for component in sorted(components_needed - classes_declared):
    component_includes += '#include "' + component + '.h"\n'

forward_decls = "\n"
for class_name in sorted(classes_declared):
    forward_decls += "class " + class_name + ";\n"


footer = "\n\n#endif\n"
code = header + component_includes + forward_decls + classes + footer
gameobjects_file = open('./src/generated/GameObjects.h','w')
gameobjects_file.write(code)

